# Generated by Django 4.2.7 on 2023-11-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available_end_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='available_start_date',
        ),
    ]
