# Generated by Django 4.2.7 on 2023-11-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_available_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
