# Generated by Django 4.2.7 on 2023-11-11 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carrental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='car',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
