# Generated by Django 4.2.7 on 2023-11-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_car_image_height_car_image_width_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
